= Red Hat Developers Workshop Operator

A Kubernetes Operator to prepare the OpenShift workshop infrastructure for running Red Hat Developers Workshops

[IMPORTANT]
====
The Operator is under development and may undergo rapid changes
====

== Deploy

[source,bash,subs="attributes+,+macros"]
----
oc new-project rhd-workshop-infra
oc apply -n rhd-workshop-infra -f deploy/service_account.yaml
oc apply -n rhd-workshop-infra -f deploy/role.yaml
oc apply -n rhd-workshop-infra -f deploy/role_binding.yaml
oc apply -n rhd-workshop-infra -f deploy/crds/developers_v1alpha1_workshop_crd.yaml
oc apply -n rhd-workshop-infra -f deploy/operator.yaml
----

== Custom Resource(CR) Attributes

The following attributes are configurable via CR

* `create_projects`: flag to control whether to create workshop user OpenShift projects or not
* `projects`: its the list of OpenShift that need to be created for each user

== users 

The user specific configurations
   
* `create`: Flag to create users or not, default: `false`
* `prefix`: The prefix for the user, defaults to `user`
* `password`: The password for workshop users, defaults `openshift`
* `admin_password`: The OpenShift cluster-admin password defaults `superS3ret`
* `from`: The start range of users count, defaults to `0`
* `to`: The end range of users count, defaults to `50`

== stacks

The software packages to install, by default Eclipse Che will be installed.

[NOTE]
====
All software packages will be installed using Kubernetes Operators. Please check https://operatorhub.io[Operator Hub] for more information
====

`che_version`: The Eclipse Che version to be used.
`install`: Whether to install the software stacks or not, defaults to `true`

The stacks divided based on `community` and `redhat` operators

=== **community** 

The operator uses **community-operators** as the source for the following packages:

  * `knative-serving`
  * `knative-eventing`
  * `openshift-pipelines`


=== **redhat**

The operator uses **redhat-operators** as the source for the following packages:
   
   * `elastic-search`
   * `jaeger`
   * `kiali`
   * `servicemesh`

== Create a CR

The following is an example CR, remove the stacks which might not be needed for the project:

[source,yaml,subs="attributes+,+macros"]
----
apiVersion: developers.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: example-workshop
  description: "Workshop Demo"
spec:
  create_projects: True
  projects:
    - tutorial
  users:    
    create: true
    prefix: 'user'
    password: 'openshift'
    admin_password: 'superS3cret'
    from: 0
    to: 3
  stacks:
    che_version: 7.1.0
    community:
      - name: "knative-serving"
        operator: "knative-serving-operator"
        version: "0.7.1"
      - name: "pipelines"
        operator: "openshift-pipelines-operator"
        version: "0.5.2"
      - name: "knative-eventing"
        operator: "knative-eventing-operator"
        version: "0.7.0"
    redhat:
      - name: "elastic-search"
        version: "4.1.14-201908291507"
        operator: "elasticsearch-operator" 
      - name: "jaeger"
        version: "1.13.1"
        operator: "jaeger-product"   
      - name: "kiali"
        version: "1.0.5"
        operator: "kiali-ossm"
        admin_username: "admin"
        admin_password: "admin"
      - name: "servicemesh"
        version: "1.0.0"
        operator: "servicemeshoperator"
----
