= Red Hat Developers Workshop Operator

A Kubernetes Operator to prepare the OpenShift workshop infrastructure for running Red Hat Developers Workshops

[IMPORTANT]
====
The Operator is under development and may undergo rapid changes
====

== Deploy

[source,bash,subs="attributes+,+macros"]
----
oc new-project rhd-workshop-infra
oc apply -n rhd-workshop-infra -f deploy/service_account.yaml
oc apply -n rhd-workshop-infra -f deploy/role.yaml
oc apply -n rhd-workshop-infra -f deploy/role_binding.yaml
oc apply -n rhd-workshop-infra -f deploy/crds/developers_v1alpha1_workshop_crd.yaml
oc apply -n rhd-workshop-infra -f deploy/operator.yaml
----

== Custom Resource(CR) Attributes

The following attributes are configurable via CR

* `delete_workshop`: flag to delete the workshop, default `False`
* `openshift_api_server`: the openshift authentication server `oauth-openshift.openshift-authentication:6443`
* `create_projects`: flag to control whether to create workshop user OpenShift projects or not
* `projects`: its the list of OpenShift that need to be created for each user

== users 

The user specific configurations
   
* `create`: Flag to create users or not, default: `false`
* `prefix`: The prefix for the user, defaults to `user`
* `password`: The password for workshop users, defaults `openshift`
* `admin_password`: The OpenShift cluster-admin password defaults `superS3ret`
* `from`: The start range of users count, defaults to `0`
* `to`: The end range of users count, defaults to `50`

== stacks

The software packages to install, by default Eclipse Che will be installed.

[NOTE]
====
All software packages will be installed using Kubernetes Operators. Please check https://operatorhub.io[Operator Hub] for more information
====

`che_version`: The Eclipse Che version to be used.
`install`: Whether to install the software stacks or not, defaults to `true`

The stacks divided based on `community` and `redhat` operators

=== **community** 

The operator uses **community-operators** as the source for the following packages:

  * `knative-serving`
  * `knative-eventing`
  * `openshift-pipelines`


=== **redhat**

The operator uses **redhat-operators** as the source for the following packages:
   
   * `elastic-search`
   * `jaeger`
   * `kiali`
   * `servicemesh`

== Create a custom resource (CR)

Create an custom resource called **Workshop**, checkout the link:./deploy/crds/cr-example.yaml[Example]