---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines
  namespace: openshift-operators
spec:
  channel: dev-preview
  source: rhd-workshop-packages
  name: openshift-pipelines-operator
  sourceNamespace: openshift-operators