apiVersion: developers.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: example-workshop
  description: "Workshop Demo"
spec:
  create_projects: True
  projects:
    - tutorial
  users:    
    create: True
    prefix: 'user'
    password: 'openshift'
    admin_password: 'superS3cret'
    from: 0
    to: 50
  stacks:
    che_version: 7.1.0
    community:
      - name: "knative-serving"
        operator: "knative-serving-operator"
        version: "0.7.1"
      - name: "knative-eventing"
        operator: "knative-eventing-operator"
        version: "0.7.1"
      - name: "pipelines"
        operator: "openshift-pipelines-operator"
        version: "0.5.2"
    redhat:
      - name: "elastic-search"
        version: "4.1.14-201908291507"
        operator: "elasticsearch-operator" 
      - name: "jaeger"
        version: "1.13.1"
        operator: "jaeger-product"   
      - name: "kiali"
        version: "1.0.5"
        operator: "kiali-ossm"
        admin_username: "admin"
        admin_password: "admin"
      - name: "servicemesh"
        version: "1.0.0"
        operator: "servicemeshoperator"