apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhd-workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rhd-workshop-operator
  template:
    metadata:
      labels:
        name: rhd-workshop-operator
    spec:
      serviceAccountName: rhd-workshop-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "quay.io/rhdevelopers/rhd-workshop-operator:v0.0.2"
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "quay.io/rhdevelopers/rhd-workshop-operator:v0.0.2"
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rhd-workshop-operator"
      volumes:
        - name: runner
          emptyDir: {}
