kind: DeploymentConfig
apiVersion: v1
metadata:
  labels:
    app: kubernetes-image-puller
  name: kubernetes-image-puller
  namespace: rhd-workshop-infra
spec:
  replicas: 1
  selector:
    app: kubernetes-image-puller
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: kubernetes-image-puller
    spec:
      containers:
      - name: kubernetes-image-puller
        image: quay.io/rhdevelopers/kubernetes-image-puller:1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: k8s-image-puller
      serviceAccountName: k8s-image-puller