---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-image-puller
  namespace: rhd-workshop-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-daemonset
  namespace: rhd-workshop-infra
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-daemonset
  namespace: rhd-workshop-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-daemonset
subjects:
- kind: ServiceAccount
  name: k8s-image-puller
  namespace: rhd-workshop-infra
