- name: "OpenShift Pipelines Operator Fact"
  vars:
    stack_pipelines_query: "community[?name=='pipelines'] | [0]"
  set_fact:
    stack_pipelines: "{{ stacks|json_query(stack_pipelines_query) }}"

### OpenShift Pipelines (Tekton)

- name: "Create OpenShift Pipelines subscription"
  k8s:
   state: present
   definition: "{{ lookup('file','subscriptions/pipelines/subscription.yaml') }}"
  register: pipelines_sub_created

- name: "Lookup OpenShift Pipelines csv"
  vars:
    pipelines_csv_lookup: "{{ lookup('k8s', api_version='operators.coreos.com/v1alpha1', kind='ClusterServiceVersion', resource_name='openshift-pipelines-operator.v'+stack_pipelines.version, namespace='openshift-operators' ) }}"
  block:
  - debug:
      msg: "Waiting OpenShift Pipelines csv to be available"
    until: pipelines_csv_lookup.status is defined and pipelines_csv_lookup.status.phase == 'Succeeded' and pipelines_csv_lookup.status.reason == 'InstallSucceeded'
    retries: 8
    delay: 10
  - name: "Set OpenShift Pipelines  csv fact"
    set_fact:
     pipelines_csv: "{{pipelines_csv_lookup }}"
